name: 'Ryan & Joes Wedding '
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: 'Ryan & Joes Wedding '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#09041c'
    - '#fcfcfc'
    - '#962e64'
    - '#5c5c7a'
    - '#f0adaf'
  brandStrength: 0
  lightness: 0.3338491227477789
  saturation: 0.5
  rhythmicContrast: 0.6375352258328348
purpose: []
